In [3]:
%matplotlib inline
import cv2
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np
import time as t
print ("OpenCV Version : %s " % cv2.__version__)

from scipy import signal
from scipy import misc

from sklearn import neighbors, datasets


OpenCV Version : 4.5.5 


<p style="font-size:300%; background-color:pink; color:blue; text-align:center;line-height : 80px; margin : 0; padding : 0;">
Tarea 10</p>
<p style="font-size:240%; background-color:pink; color:red; text-align:center;line-height : 60px; margin : 0; padding : 0;">
Técnicas de Inteligencia Artificial - Visión de Máquina</p1>

<p style="font-size:200%; text-align:center; line-height : 40px;  margin-top : 0; margin-bottom : 0; "> <br> Eduardo Garnica Aza</p>
<p style="font-size:180%; text-align:center; line-height : 30px;  margin-top : 0; margin-bottom : 0; "> <br><br>INGENIERIA MECATRONICA</p>
<p style="font-size:180%; text-align:center; line-height : 30px; margin-top : 0; "> Facultad de Ingeniería</p>
<p style="font-size:160%; text-align:center; line-height : 30px; margin-top : 0; "> Universidad Nacional de Colombia Sede Bogotá</p>
<br>
<img src="Escudo_UN.png",width=100,height=100>
<p style="font-size:160%; text-align:center; line-height : 30px; margin-top : 0; "> <br>21 de abril de 2022</p>

# valores propios y vectores propios del conjunto de datos.

In [4]:
from pylab import plot,subplot,axis,stem,show,figure
from numpy import mean,cov,double,cumsum,dot,linalg,array

#Datos = np.array([ [2.5,2.4], [0.5,0.7], [2.2,2.9], [1.9,2.2], [3.1,3.0], [2.3,2.7],
             #[2.0,1.6], [1.0,1.1], [1.5,1.6], [1.1,0.9]])

Datos = np.array([ [98,81,38], [103,84,38], [103,86,42], [105,86,42], [109,88,44], [123,95,46],
     [134,100,48], [136,102,49], [123,92,50], [133,99,51], [133,102,51] , [133,102,51],
     [138,98,51], [138,99,51], [141,105,53], [149,107,55], [153,107,56], [147,108,57], 
     [155,117,60], [158,115,62], [155,115,63], [159,118,63], [162,124,61], [177,132,67]])


In [5]:
mean = np.empty((0))
mean, eigvector  = cv2.PCACompute(Datos.astype(double), mean)

print ("\nMedia")
print (mean)
print ("\nEigenVectors") # Mostrados en Filas
print (eigvector)

print ("\nValores propios")
MC = np.cov(Datos.transpose())  
for i in range (eigvector.shape[0]):
    eigenValue = np.dot(np.dot(eigvector[i].transpose(), MC), eigvector[i])/ np.dot(eigvector[i].transpose(), eigvector[i])
    print (eigenValue)


Media
[[136.04166667 102.58333333  52.04166667]]

EigenVectors
[[ 0.81388081  0.4961059   0.30245159]
 [-0.55489628  0.81802677  0.15140118]
 [-0.17230248 -0.29105178  0.94106361]]

Valores propios
678.3656506923961
6.769697241098388
2.85378250128809
